armor_detector:
  cv: #装甲板灯条完整无损坏才可以用
    enable: false
    armor:
      max_angle: 40
      max_large_center_distance: 8
      max_small_center_distance: 3.5
      min_large_center_distance: 3.5
      min_light_ratio: 0.5
      min_small_center_distance: 0.05
    light:
      binary_thres: 150
      expand_ratio_h: 1.9
      expand_ratio_w: 1.2
      max_angle: 45
      max_ratio: 0.4
      min_ratio: 0.01
      max_pts_error: 20.0
      max_angle_diff: 20.0
      color_diff_thresh: 0
  classify:
    enable: true
    label_path: ${VISION_ROOT}/model/label.txt
    model_path: ${VISION_ROOT}/model/mlp.onnx
    backend: opencv
    threshold: 0.5
  
  tensorrt:
    conf_threshold: 0.2
    model_path: ${VISION_ROOT}/model/opt-1208-001.onnx
    device_id: 0
    nms_threshold: 0.3
    top_k: 128
    max_infer_running: 3
    min_free_mem_ratio: 0.1
    use_cuda_pre: true
    log_time: false
    model_type: tup
  openvino:
    conf_threshold: 0.2
    device_name: GPU
    model_path: ${VISION_ROOT}/model/opt-1208-001.onnx
    nms_threshold: 0.3
    top_k: 128
    use_throughputmode: true
    model_type: tup
  onnxruntime:
    conf_threshold: 0.2
    model_path: ${VISION_ROOT}/model/opt-1208-001.onnx
    nms_threshold: 0.3
    top_k: 128
    model_type: tup
    provider: CUDA
  ncnn:
    conf_threshold: 0.2
    model_path_param: ${VISION_ROOT}/model/opt-1208-001.param
    model_path_bin: ${VISION_ROOT}/model/opt-1208-001.bin
    input_name: images
    output_name: output
    use_gpu: true
    use_lightmode: false
    device_id: 0
    cpu_threads: 20
    nms_threshold: 0.3
    top_k: 128
    model_type: tup
