armor_detect_backend: tensorrt
max_detect_armors: 11


armor_map:
  SENTRY: 4
  NO1: 2
  NO2: 3
  NO3: 4
  NO4: 5
  NO5: 9
  OUTPOST: 6
  BASE: 7
  UNKNOWN: -1

armor_where:
  yaw_opt:
    mode: golden
    golden_search_side_deg: 60
  distance_fix_a2: 0.0

armor_tracker:
  lost_time_thres: 2.0
  tracking_thres: 10
  max_yaw_diff_deg: 60.0
  max_dis_diff: 3.0
  match_gate: 50
  qxyz_common: [200.0, 200.0, 1.0]
  qyaw_common: 100.0
  qxyz_output: [10.0, 10.0, 0.5]
  qyaw_output: 0.01
  q_r: 0.0000001
  q_l: 0.0000001
  q_h: 0.0000001
  q_outpost_dz: 0.5
  yp_r: 2e-3
  dis_r_front: 0.5
  dis_r_side: 2.5
  dis2_r_ratio: 0.1
  yaw_r_base_front: 0.2
  yaw_r_base_side: 0.06
  yaw_r_log_ratio: 0.02
  esekf_iter_num: 5


auto_aim_fsm:
  single_whole_up: 2.5 
  single_whole_down: 1.0
  whole_pair_up: 7.5 
  whole_pair_down: 6.5 #1s内至少换2次板子  2pi  否则轨迹规划无意义
  pair_center_up: 16.5
  pair_center_down: 15.0
  transfer_thresh: 50

very_aimer:
  type: "seg" #seg or mpc
  
  sample_total_time: 2.0
  
  sample_horizon: 500

  control_delay: 0.1
  delay_enable_fire_error: 0.0035
  
  max_yaw_acc: 40
  #全向yaw加速度测算37
  max_pitch_acc: 25
  

  prediction_delay: -0.01 
  comming_angle: 60
  leaving_angle: 20

  yaw_limit_deg: 40
  shooting_range_h: 0.1
  shooting_range_w: 0.1
  min_enable_pitch_deg: 0.25
  min_enable_yaw_deg: 0.25
  base_offset:
      yaw: -2.0
      pitch: 0.0
  trajectory_offset:
    - d_max: 3
      d_min: 0
      h_max: 1.5
      h_min: -1
      pitch_off: 0
      yaw_off: 0
    - d_max: 4.5
      d_min: 3
      h_max: 1.5
      h_min: -1
      pitch_off: 0
      yaw_off: 0
    - d_max: 4.5
      d_min: 9
      h_max: 1.5
      h_min: -1
      pitch_off: 0
      yaw_off: 0
  #---mpc only
  max_iter: 10
  Q_yaw: [7e6, 0]
  R_yaw: [3.0]
  Q_pitch: [7e6, 0]
  R_pitch: [3.0]


  
trajectory_compensator:
  compenstator_type: resistance
  gravity: 9.8
  iteration_times: 20
  resistance: 0.092
  k1: 0.0190 #大弹丸double k1_c = 0.47; double k1 = k1_c * 1.169 * (2 * M_PI * 0.02125 * 0.02125) / 2 / 0.041;



auto_exposure:
  enable: true
  target_brightness: 25.0
  tolerance: 3.0
  step_gain: 15.0
  decay_step: 1.0
  exposure_min: 100.0
  exposure_max: 1500.0
  control_interval_ms: 300
