rune_detect_backend: tensorrt

rune_solver:
  auto_type_determined: true
  compensator_type: resistance
  ekf:
    iteration_num: 1
    q_xyzyaw:
      - 4e-4
      - 4e-4
      - 4e-4
      - 4e-4
    r_xyzyaw:
      - 4e-2
      - 4e-2
      - 4e-2
      - 4e-2
  gravity: 9.8
  lost_time_thres: 0.5
  predict_offset: 0.1
  trajectory_offset:
    - d_max: 6
      d_min: 5
      h_max: 0.4
      h_min: -1
      pitch_off: 0.1
      yaw_off: 0
