armor_detect_backend: tensorrt
max_detect_armors: 11
use_ba: true

armor_optimize:
  max_iter_R: 300
  max_iter_t: 1000
  step_R: 30
  step_t: 100
  min_error_R: 0.7
  min_error_t: 0.5
  distance_fix_a2: 0.00

armor_tracker:
  lost_time_thres: 1.0
  tracking_thres: 10
  max_yaw_diff_deg: 80.0
  max_dis_diff: 1.0
  qxyz_common: 100.0
  qyaw_common: 50.0
  qxyz_output: 10.0
  qyaw_output: 0.1
  yp_r: 4e-3
  dis_r_front: 0.5
  dis_r_side: 1.5
  dis2_r_ratio: 0.005
  yaw_r_base_front: 0.09
  yaw_r_base_side: 0.06
  yaw_r_log_ratio: 0.005

auto_aim_fsm:
  thres_up_1: 3.5
  thres_down_1: 2.0
  thres_up_2: 16.5
  thres_down_2: 15.0
  transfer_thresh: 20

planner:
  max_yaw_acc: 50
  Q_yaw: [9e6, 0]
  R_yaw: [1.5]

  max_pitch_acc: 100
  Q_pitch: [9e6, 0]
  R_pitch: [1]

aimer:
  prediction_delay: 0.00
  comming_angle: 60
  leaving_angle: 20

shooter:
  shooting_range_h: 0.01
  shooting_range_w: 0.01
  trajectory_offset:
    - d_max: 9
      d_min: 0
      h_max: 1.4
      h_min: -1
      pitch_off: -0.0
      yaw_off: -1.0
    - d_max: 10
      d_min: 9
      h_max: 0.4
      h_min: -1
      pitch_off: -1.3
      yaw_off: 0

trajectory_compensator:
  compenstator_type: ideal
  gravity: 9.8
  iteration_times: 20
