armor_detect_backend: tensorrt
max_detect_armors: 11


armor_map:
  SENTRY: 4
  NO1: 2
  NO2: 3
  NO3: 4
  NO4: 5
  NO5: 9
  OUTPOST: 6
  BASE: 7
  UNKNOWN: -1

armor_optimize:
  enable: true
  mode: golden
  ceres_max_iter: 100
  golden_search_side_deg: 60
  distance_fix_a2: 0.0

armor_tracker:
  lost_time_thres: 2.0
  tracking_thres: 10
  max_yaw_diff_deg: 70.0
  max_dis_diff: 3.0
  match_gate: 5
  qxyz_common: 200.0
  qyaw_common: 10.0
  qxyz_output: 10.0
  qyaw_output: 0.1
  q_r: 0.0
  q_l: 0.0
  q_h: 0.0000001
  q_outpost_dz: 0.5
  yp_r: 2e-3
  dis_r_front: 0.5
  dis_r_side: 2.5
  dis2_r_ratio: 0.1
  yaw_r_base_front: 0.2
  yaw_r_base_side: 0.06
  yaw_r_log_ratio: 0.02
  esekf_iter_num: 5

auto_aim_fsm:
  thres_up_1: 3.5
  thres_down_1: 2.0
  thres_up_2: 16.5 
  thres_down_2: 15.0
  transfer_thresh: 20

# auto_aim_fsm:
#   thres_up_1: 1.0
#   thres_down_1: 0.5
#   thres_up_2: 3.0 
#   thres_down_2: 2.0
#   transfer_thresh: 20

very_aimer:
  max_iter: 10
  control_delay: 0.01
  delay_enable_fire_error: 0.0035
  max_yaw_acc: 40
  #全向yaw加速度测算37
  Q_yaw: [7e6, 0]
  R_yaw: [3.0]

  max_pitch_acc: 25
  Q_pitch: [7e6, 0]
  R_pitch: [3.0]

  prediction_delay: -0.0 
  comming_angle: 60
  leaving_angle: 20

  yaw_limit: 40
  shooting_range_h: 0.1
  shooting_range_w: 0.1
  min_enable_pitch_deg: 0.25
  min_enable_yaw_deg: 0.25
  base_offset:
      yaw: -3.5
      pitch: -3.8
  trajectory_offset:
    - d_max: 3
      d_min: 0
      h_max: 1.5
      h_min: -1
      pitch_off: 0
      yaw_off: 0
    - d_max: 4.5
      d_min: 3
      h_max: 1.5
      h_min: -1
      pitch_off: 0
      yaw_off: 0
    - d_max: 4.5
      d_min: 9
      h_max: 1.5
      h_min: -1
      pitch_off: 0
      yaw_off: 0

  
trajectory_compensator:
  compenstator_type: resistance
  gravity: 9.8
  iteration_times: 20
  resistance: 0.092



auto_exposure:
  enable: true
  target_brightness: 25.0
  tolerance: 3.0
  step_gain: 15.0
  decay_step: 1.0
  exposure_min: 100.0
  exposure_max: 3500.0
  control_interval_ms: 300
