type: video_player

camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"

hik_camera:
  target_sn: DA1094119
  acquisition_frame_rate: 250
  adc_bit_depth: Bits_8
  exposure_time: 2500
  gain: 16.9
  gamma: 0.7 #Bayer用不了
  pixel_format: BayerRG8 #RGB8Packed
  acquisition_frame_rate_enable: true
  reverse_x: false
  reverse_y: false
  recorder: false

video_player:
  fps: 200
  loop: true
  #path: /home/hy/wust_data/video/222.MP4
  path: /home/hy/wust_data/video/jiao.avi
  #path: /home/hy/Z_LION_AutoAim2025/src/auto_aim_publisher/videos/sample.avi
  #path: /home/hy/data/4k.MP4
  #path: /home/hy/wust_data/video/rune.mp4
  #path: /home/hy/wust_data/video/Sentry.mp4
  start_frame: 0
