max_infer_running: 6
detect_color: 0
attack_mode: 0
debug_mode: true

tf:
  R_camera2gimbal: [0.0, 0.0, 1.0, -1.0, -0.0, 0.0, 0.0, -1.0, 0.0]
  t_camera2gimbal:
    [0.065434347168653831, 0.10641232476052895, 0.0436106400231024]
control:
  control_rate: 500
  communication_delay_us: 1100
  pitch_avg_windows: 20
  yaw_avg_windows: 20
  device_name: /dev/ttyACM_RMc
  use_serial: false
logger:
  log_level: INFO
  log_path: /home/hy/wust_log
  use_logcli: true
  use_logfile: true
  use_simplelog: true
shoot:
  bullet_speed: 18.0
  controller_delay: 0.00

auto_exposure:
  enable: true
  target_brightness: 15.0
  tolerance: 3.0
  step_gain: 15.0
  decay_step: 1.0
  exposure_min: 100.0
  exposure_max: 2500.0
  control_interval_ms: 300


use_sim: true
