max_infer_running: 6
detect_color: 0
attack_mode: 0
debug_fps: 60
tf:
  R_camera2gimbal: [0.0, 0.0, 1.0, -1.0, -0.0, 0.0, 0.0, -1.0, 0.0]
  t_camera2gimbal:
    [0.065434347168653831, 0.10641232476052895, 0.0436106400231024]
control:
  control_rate: 1000
  communication_delay_us: 1000
  device_name: /dev/ttyACM0
  use_serial: false
  yaw_ramp: 0.0  #send_cmd = cmd.pos+cmd.vel*ramp
  pitch_ramp: 0.0
  
logger:
  log_level: DEBUG
  log_path: log
  use_logcli: true
  use_logfile: false
  use_simplelog: true

shoot:
  bullet_speed: 22.0
  rate: 10

record:
  use_record: false
  folder_path: record
  use_rotate_reader: false
  read_csv_path: ""


