max_infer_running: 1
detect_color: 0
attack_mode: 0
debug_fps: 60
tf:
  R_camera2gimbal: [0.0, -0.2079117, 0.9781476,-1.0, 0.0, 0.0,0.0, -0.9781476, -0.2079117] #英雄
  t_camera2gimbal:
    [0.000434347168653831, -0.10141232476052895, 0.00736106400231024]
control:
  control_rate: 1000
  communication_delay_us: 100.000
  device_name: /dev/ttyACM0
  use_serial: true
  yaw_ramp: 0.0  #send_cmd = cmd.pos+cmd.vel*ramp
  pitch_ramp: 0.0
  
logger:
  log_level: DEBUG
  log_path: log
  use_logcli: true
  use_logfile: false
  use_simplelog: true

shoot:
  bullet_speed: 16.0
  rate: 2

record:
  use_record: false
  folder_path: record
  use_rotate_reader: false
  read_csv_path: ""


