common:
  armor_detect_backend: tensorrt
  rune_detect_backend: tensorrt
  detect_color: 0
  init_attack_mode: 0
  max_detect_armors: 12
  max_infer_running: 10
  thread_multiplier: 2
  only_nav_enable: false
  use_auto_labeler: false
  use_calculation: false
  use_ba: false
  use_omni: false
  hit_omni_dt: 5.0
  receive_omni_dt: 1.0

camera:
  target_sn: DA1094119
  acquisition_frame_rate: 200
  adc_bit_depth: Bits_8
  camera_info_path: /home/hy/wust_vision/config/camera_info.yaml
  exposure_time: 1000
  gain: 16.9
  gamma: 0.7 #Bayer用不了
  pixel_format: BayerRG8 #RGB8Packed
  acquisition_frame_rate_enable: true
  reverse_x: false
  reverse_y: false
  recorder: true
  use_high_priority: true
  high_priority_cpu_id: 3
  high_priority_cpu_priority: 90
  use_sched_fifo: true
  video_player:
    fps: 200
    use_high_priority: true
    high_priority_cpu_id: 3
    high_priority_cpu_priority: 90
    use_sched_fifo: true
    loop: true
    #path: /home/hy/wust_data/video/222.MP4
    #path: /home/hy/wust_data/video/20250726_233351.avi
    path: /home/hy/wust_data/video/jiao.avi
    #path: /home/hy/wust_data/video/aaa.mp4
    #path: /home/hy/wust_data/video/rune.mp4
    #path: /home/hy/wust_data/video/Sentry.mp4
    start_frame: 500
    alpha: 1.0
    beta: 0
    use: true

control:
  alpha_pitch: 0.7
  alpha_yaw: 0.5
  control_rate: 2000
  communication_delay: 1000
  device_name: /dev/ttyACM0
  max_pitch_change: 5
  max_yaw_change: 10
  jump_yaw: 1.0
  use_nav: false
  use_serial: false

tf:
  gimbal2camera_pitch: 0
  gimbal2camera_roll: 0
  gimbal2camera_x: 0.07
  gimbal2camera_y: 0.05
  gimbal2camera_yaw: 0.5
  gimbal2camera_z: 0.0

debug:
  debug_mode: true
  debug_h: 1080
  debug_w: 1440
  debug_show_dt: 0.01
  debug_fps: 30

logger:
  log_level: INFO
  log_path: /home/hy/wust_log
  use_logcli: true
  use_logfile: true
  use_simplelog: true

shoot:
  bullet_speed: 21

armor_optimize:
  max_iter_R: 3000
  max_iter_t: 1000
  step_R: 100
  step_t: 100
  min_error_R: 5
  min_error_t: 0.5
  distance_fix_a2: 0.01

armor_solver:
  compenstator_type: ideal
  controller_delay: 0.01
  gravity: 9.8
  iteration_times: 20
  min_switching_v_yaw: 1
  max_tracking_v_yaw: 180
  prediction_delay: 0.0
  resistance: 0.092
  small_shooting_range_h: 0.12
  small_shooting_range_w: 0.09
  big_shooting_range_h: 0.2
  big_shooting_range_w: 0.15
  side_angle: 20
  oneswitch_position_thres: 0.5
  oneswitch_angle_thres: 30
  oneswitch_hold_time: 1.5
  trajectory_offset:
    - d_max: 4
      d_min: 0
      h_max: 0.4
      h_min: -1
      pitch_off: -1.5
      yaw_off: 20
    - d_max: 7
      d_min: 4
      h_max: 0.4
      h_min: -1
      pitch_off: -1.3
      yaw_off: 0

armor_tracker:
  ekf:
    use_esekf: false
    fusion_esekf_ekf: true
    iteration_num: 2
    oyr_d_front: 0.0002 #1m处
    oyr_d_side: 0.0007 #1m处
    oyr_p: 1 #角度
    oyr_y: 1 #角度
    oyr_yaw_front: 8
    oyr_yaw_side: 5
    oys2qx: 40
    oys2qy: 40
    oys2qyaw: 30
    oys2qz: 5
    yr_d_front: 0.02 #1m处
    yr_d_side: 0.07 #1m处
    yr_p: 10 #角度
    yr_y: 7 #角度
    yr_yaw_front: 8
    yr_yaw_side: 8
    ys2qd_zc: 700
    ys2qr: 70
    ys2qx: 22
    ys2qy: 22
    ys2qyaw: 35
    ys2qz: 1.0
    r_v: 20
    q_v: 5.0
    q_a: 1.0
  jump_thresh: 0.4
  lost_time_thres: 0.9
  max_match_distance: 0.5
  max_match_yaw_diff: 0.5
  max_match_z_diff: 0.1
  one_lost_time_thres: 0.1
  tracking_thres: 5
  one_tracking_thres: 1
  v_yaw_to_one_thres_high: 1.0
  v_yaw_to_one_thres_low: 0.5
  track_one_num: 2

rune_solver:
  auto_type_determined: true
  compensator_type: resistance
  ekf:
    iteration_num: 1
    q_ypdyaw:
      - 2e-4
      - 1e-4
      - 1e-4
      - 1e-4
    r_ypdyaw:
      - 1
      - 1
      - 0.0005
      - 5
  gravity: 9.8
  lost_time_thres: 0.5
  predict_offset: 0.1
  trajectory_offset:
    - d_max: 6
      d_min: 5
      h_max: 0.4
      h_min: -1
      pitch_off: 0.1
      yaw_off: 0
