armor_detector:
  light:
    binary_thres: 70
    max_angle: 40
    max_ratio: 0.4
    min_ratio: 0.001
    color_diff_thresh: 20
    max_angle_diff: 10.0
  armor:
    min_light_ratio: 0.8
    min_small_center_distance: 0.8
    max_small_center_distance: 3.5
    min_large_center_distance: 3.5
    max_large_center_distance: 8.0
    max_angle: 40.0
  classify:
    label_path: ${VISION_ROOT}/model/label.txt
    model_path: ${VISION_ROOT}/model/reborn_number_classifier.onnx
    threshold: 0.5
