armor_detect_opencv:
  light:
    binary_thres: 85
    max_angle: 40
    max_ratio: 0.6
    min_ratio: 0.01
    color_diff_thresh: 20
  armor:
    min_light_ratio: 0.8
    min_small_center_distance: 0.8
    max_small_center_distance: 3.5
    min_large_center_distance: 3.5
    max_large_center_distance: 8.0
    max_angle: 30.0
  classify:
    label_path: /home/hy/wust_vision/model/label.txt
    model_path: /home/hy/wust_vision/model/mlp.onnx
    threshold: 0.7
